name: md-docs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [test-execution-changed]

jobs:

  md-docs:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download
        uses: synionnl/md-docs-actions/azure/download@main
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          storage_account: synionstorage
          storage_container: test-executions
          github_token: ${{ github.token }}
          repository: ${{ github.repository }}

      - name: Build
        uses: synionnl/md-docs-actions/build@main

      - name: Deploy
        uses: synionnl/md-docs-actions/azure/deploy@main
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          storage_account: synionstorage
          storage_container: docs-synion-nl
          storage_bucket: products
          cdn_resource_group: synion
          cdn_profile: synion-cdn
          cdn_endpoint: docs-synion-www